### ISSUE TITLE
Notification screen [UI][Noodle] 🔔🔔🔔🔔

### ISSUE THREAD

**Issue by chungquantin** [RamenTeam/ramen#48]
![friendrequest_android_facebook_uigarage](https://user-images.githubusercontent.com/56880684/115909822-3e2b3200-a496-11eb-9018-0af650783498.jpg)

@Kasturez Please take care of this part!

@tratng02 Prepare the FCM for push notification on foreground!

@chungquantin Doing on the background notification. Research more from this https://towardsdatascience.com/designing-notification-system-with-message-queues-c30a2c9046de

**Comment by Kasturez** [comment]
add badge package for showing a number on an Icon,

**Comment by khaitruong922** [comment]
Next: Fetch notification from API
