### ISSUE TITLE
Connection + Notification bug

### ISSUE THREAD

**Issue by khaitruong922** [RamenTeam/ramen#68]
1. If two users send connect request to each other and one accepts, the notification still exists on the other user.
- How to fix : Discard the pending notification that the other user sent.

2. The user can still send connect request to another user even they are already connected (may because the connect request does not exist anymore)
- How to fix: Not allow the user to send connect request to another user when they are already connected.

TODO: Remove connection (unfriend)

**Comment by khaitruong922** [comment]
This can make the notification removed on the other user front-end. 

We may need a OnNotificationRemoved event to handle this 
or
OnNotificationChanged when the number of notifications changed -> return all notifications (prefer this)

**Comment by khaitruong922** [comment]
Suggested feature: Cancel connection request

**Comment by chungquantin** [comment]
Fixed!
