### ISSUE TITLE
Remote camera not shown issue

### ISSUE THREAD

**Issue by khaitruong922** [RamenTeam/ramen#71]
Success cases:
- @Kasturez Web with @Kasturez phone 
- @Kasturez Web with @chungquantin Web

Fail cases: 
- @Kasturez Phone with @chungquantin Web (only @chungquantin can view the remote video)
- All cases with @khaitruong922

**Comment by chungquantin** [comment]
Poor @khaitruong922 !

**Comment by khaitruong922** [comment]
> Poor @khaitruong922 !

sadv

**Comment by khaitruong922** [comment]
sad
